spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/arto         #??? ??? ?? ??
    username: artoroot                            #??? ??? ?? ??
    password: ArtoRoot123!@#                      #??? ??? ?? ??

  # spring.jpa.hibernate.ddl-auto
  jpa:
    hibernate:
      ddl-auto: update                            #update / none ? ?? | ?? ?? ??? ??? ??
    properties:
      hibernate:
        format_sql: true
    show-sql: true
